# Generated by Django 5.2.6 on 2025-09-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_rut_historialmedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
    ]
