# Generated by Django 5.2.6 on 2025-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_orden_total_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre_completo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
