# Generated by Django 5.2.6 on 2025-09-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_arancel_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='tipo',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELEMEDICINA', 'Telemedicina'), ('LABORATORIO', 'Laboratorio')], default='PRESENCIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_examen', models.CharField(max_length=255)),
                ('archivo_resultado', models.FileField(upload_to='resultados_laboratorio/')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.paciente')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
        ),
    ]
